### PR TITLE
Fix fontSizeThatFits with label empty text

### LINKED ISSUE #15: fontSizeThatFits() does not work when text is ""!
I just added a label to the storyboard, set up the constraints so that its bounds fills the whole screen. Then, in `viewDidLayoutSubviews`, I did this:

```
    // note that the label's text is not empty string here
    print(label.fontSizeThatFits(text: "00:00", maxFontSize: 500))
    print(label.fontSizeThatFits(text: "00:00:00", maxFontSize: 500))
```

And the values printed seems good. The first is larger than the second.

But if I do this:

```
    label.text = ""
    print(label.fontSizeThatFits(text: "00:00", maxFontSize: 500))
    print(label.fontSizeThatFits(text: "00:00:00", maxFontSize: 500))
```

It prints 17 and 17!

After looking into the source code, I think there is something wrong with the `currentAttributedStringAttributes()` method. But I'm quite inexperienced in dealing with `NSAttributedString`s so I can't figure out what is wrong.

Can you fix this?

### PR DESCRIPTION
**Pull request by tbaranes**
Closed #15

### CODE REVIEW

**Comment by Sweeper777** [comment]
I tried this in my own code and it still returns the incorrect font size.
I tested the test you added and it failed too.
This is so confusing...

Any ideas why?

**Comment by tbaranes** [comment]
Since, the tests passed, their definitely an issue 😆 
Are you using the right branch? Did you try to clean the project? Build the framework separately?

**Comment by Sweeper777** [comment]
I cleaned and the tests passed! But it's still not working in my own code though. But I found an alternate solution. Anyway, you can merge the PR now.

**Comment by tbaranes** [comment]
What was your issue? What is your workout? Just interested in order to confirm that's the right solution

**Comment by Sweeper777** [comment]
Okay, I am writing a timer app. And the label I used to display the remaining time is an `LTMorphingLabel`. I want this label to fill the screen. For timers set to 1 hour or below, I display the remaining time in "XX:XX" format. (I call this a short description timer) And for timers set to 1 hour+, I display the remaining time in "XX:XX:XX" format. (I call this a long description timer)

So I originally thought calling `fontSizeToFit` each time the timer changes from a short description to a long description and vice versa would work. However, due to an issue in `LTMorphingLabel`, changing the font size of the label will mess up the text. [see here](https://github.com/lexrus/LTMorphingLabel/issues/62). At the "messed up" state, changing the text of the label can fix the mess.

So that's why I need the `fontSizeThatFits` method. I need to know what the font size would be without changing the text, because if i changed the text before setting the font size, it messes up. Instead of doing this:

```
timerLabel.text = timer.description
timerLabel.fontSizeToFit(maxFontSize: 500)
```

I need to do this:

```
    timerLabel.text = "" // set the text to something that doesn't matter
    shortFontSize = timerLabel.fontSizeThatFits(text: "00:00", maxFontSize: 500)
    longFontSize = timerLabel.fontSizeThatFits(text: "00:00:00", maxFontSize: 500)

    // actually setting the font size. This will mess up the text. But it doesn't matter because the text is empty anyways.
    timerLabel.font = timerLabel.font.fontWithSize(timer.hasLongDescription ? longFontSize : shortFontSize)
    timerLabel.text = timer.description // now I can set the text back to the value I intended to set.
```

But because of #15, I have to set the label's text to empty _after_ calling `fontSizeThatFits`:

```
    shortFontSize = timerLabel.fontSizeThatFits(text: "00:00", maxFontSize: 500)
    longFontSize = timerLabel.fontSizeThatFits(text: "00:00:00", maxFontSize: 500)
    timerLabel.text = "" // set the text to something that doesn't matter

    // actually setting the font size. This will mess up the text. But it doesn't matter because the text is empty anyways.
    timerLabel.font = timerLabel.font.fontWithSize(timer.hasLongDescription ? longFontSize : shortFontSize)
    timerLabel.text = timer.description // now I can set the text back to the value I intended to set.
```

**Comment by tbaranes** [comment]
Thanks for the explanation! I have a better understand on your context now :)
I'm merging this now.

**Pull request merged**
