### PR TITLE
added fontSizeThatFits

### PR DESCRIPTION
**Pull request by Sweeper777**

### CODE REVIEW

**Comment by tbaranes** [comment]
Nice work! Just few minor feedbacks:
- Can you refactor `fontSizeToFit` to make it use `fontSizeThatFits`? Let's avoid a big duplicate
- Can you add an entry in the `CHANGELOG`?
- Can you add an entry in the `README`?

Otherwise 👍

**Comment by Sweeper777** [comment]
Okay, I'll do them tomorrow coz I'm going to sleep now.

**Comment by Sweeper777** [comment]
I've done it now. Please take a look.

**Comment by tbaranes** [comment]
That's perfect! Thanks for the contribution 🎉

**Pull request merged**
